config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'homee/index'

  root 'homee#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end
class User < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@facebook.com",
                            password:Devise.friendly_token[0,20]
                          )
      end
       
    end
  end



    def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
 
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  if user
    return user
  else
    registered_user = User.where(:email => auth.uid + "@twitter.com").first
    if registered_user
      return registered_user
    else
    	p "#####"
      user = User.create(
        provider:auth.provider,
        uid:auth.uid,
        email:auth.uid+"@twitter.com",
        password:Devise.friendly_token[0,20]
      )
    end
  end
 end
 
 def self.find_for_linkedin_oauth(auth, signed_in_resource=nil)
 
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  if user
    return user
  else
    registered_user = User.where(:email => auth.uid + "@linkedin.com").first
    if registered_user
      return registered_user
    else
      
      user = User.create(
        provider:auth.provider,
        uid:auth.uid,
        email:auth.uid+"@linkedin.com",
        password:Devise.friendly_token[0,20]
      )
    end
  end
 end

 def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20]
        )
      end
   end
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/homee_controller.rb
class HomeeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name", disposition: 'attachment'   # Excluding ".pdf" extension.
      end
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json

  def show
    
  end
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:pro_title, :pro_des, :userid)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    auth = env["omniauth.auth"]
    #Rails.logger.info("auth is **************** #{auth.to_yaml}")
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end 
  
  def linkedin
    auth = env["omniauth.auth"]
    #Rails.logger.info("auth is **************** #{auth.to_yaml}")
    @user = User.find_for_linkedin_oauth(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.linkedin_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end 


  def google_oauth2
     
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homee_helper.rb
module HomeeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/homee/index.html.erb
<div align="center">
<% unless user_signed_in? %>

<%= link_to "Login Using E-mail", new_user_session_path, :class => 'navbar-link btn btn-default'  %> 
 <p>OR</p>

<%= link_to user_facebook_omniauth_authorize_path do %>
	<i class="fa fa-facebook circle"></i>
<% end %>
<%= link_to user_twitter_omniauth_authorize_path do %>
	<i class="fa fa-twitter circle"></i>
<% end %>
<%= link_to user_linkedin_omniauth_authorize_path do %>
	<i class="fa fa-linkedin circle"></i>
<% end %>
<%#= link_to "Sign in with Google", user_google_omniauth_authorize_path %>
</div>
<% end%>

 <% if user_signed_in? %>
	<%= link_to "Project Creation", new_product_path, :class => 'navbar-link btn btn-default' %>
	<%= link_to "projects View", products_path, :class => 'navbar-link btn btn-default' %>
	<%= link_to "Download Pdf", products_path(format: :pdf), :class => 'navbar-link btn btn-default' %>
 <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MdayApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
           
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
  			Logged in as <strong><%= current_user.email %></strong>.
  			
  			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link btn btn-default'%>
		 <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link btn btn-default'  %> |
  	      <%= link_to "Login", new_user_session_path, :class => 'navbar-link btn btn-default' %>
  	 
  	    <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
 </nav>    

 
 <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
 <% end %>
 <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
 <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div text align="center">
  <%= form_for(product) do |f| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
   
    <div class="field">
      <%= f.label :pro_title %>
      <%= f.text_field :pro_title %>
    </div>

    <div class="field">
      <%= f.label :pro_des %>
      <%= f.text_field :pro_des %>
    </div>

    <div class="field">
      <%= f.label :userid %>
      <%= f.number_field :userid %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1> 
    

<table>
  <thead>
    <tr>
      <th>Pro title</th>
      <th>Pro des</th>
      <th>Userid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.pro_title %></td>
        <td><%= product.pro_des %></td>
        <td><%= product.userid %></td>
        <td width="50"><%= link_to 'Show', product %></td> 
        <td width="50"><%= link_to 'Edit', edit_product_path(product) %></td> 
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
<%= link_to 'Home page', homee_index_path %>

app/views/products/index.pdf.erb
<h1>Products</h1> 
    

<table>
  <thead>
    <tr>
      <th>Pro title</th>
      <th>Pro des</th>
      <th>Userid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.pro_title %></td>
        <td><%= product.pro_des %></td>
        <td><%= product.userid %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<div text align="center">
   <h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pro title:</strong>
  <%= @product.pro_title %>
</p>

<p>
  <strong>Pro des:</strong>
  <%= @product.pro_des %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @product.userid %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>